# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170810_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='categroy',
            field=models.CharField(choices=[('px', '培训'), ('gr', '个人'), ('gx', '高校')], default='px', max_length=20, verbose_name='机构类型'),
        ),
    ]
