# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_categroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='categroy',
            new_name='category',
        ),
    ]
