# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170810_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_num',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='student_num',
            field=models.IntegerField(default=0, verbose_name='学生数'),
        ),
    ]
