# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170810_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
